language: node_js

sudo: false

dist: trusty

node_js:
  - "12"

addons:
  chrome: stable
  sonarcloud:
    organization: "myerffoeg"
    token:
      secure: "DbdyainMj7LgBtLmuXbZijJNpaPAhh5ZcDzF81qaZdXVq4pzRxXNokrh1PYDPhJNP6G2F22ZDLlgSn+D/85RGjdg9bdggIMo/JHNC1MraCGTCC/g86Ky3bOFTEsbnINq8ASJoHb1TFyuMAQZQ0AkEeDz4RY7fpL9pmQ3EqzSPKCn+9NvhhEn++Fhq9Df4guFgreqTSTiEEIGVr9XBdsnNmlgh4qHSrdAe/lxecBhsM+b/ruZxmIr0+Q6K8Ud1+2TkXxLDczKxR9mk+ibE9wwkQg7VfA1e04p7cpPDJ05W5MMG2W6GSEBQbrmTJtEgD7CN5z+uyoH7HUoKT/dncqYM6qOb2qELxS4Q3gMDZA5aZA/rZe/9s3IttSBwLa9i0RdeX/wfEEs0MZZilPzWcMWmCBvA4bVd75m7SHJNr+8jARpTBSy2TuQD/pVmB8ZVqUgBj1rWePfhw/B3oBgkwYyRb0oi3y8Y9M7wg0DXHv9i9g0cHeG7tsFfUpsI/TNmb2a3jCsZ8ZHyecNFkAJ2bpwhPhUzseyjeAfIYY2YC+Rp0AFAdZKWIOt+3/noxpvbOa6/vsfeI0O0W+ZmHaTS6e7M7TEsvJpw8kFV4cqm61CRq9LqXSmJpPzkl1s/jtawmadmpoTqMJUPWoAqWc4DlBxqrES7J+RvkmZrM1lEWh6xtw="

before_install:
  - npm install -g npm@latest

install:
  - npm install

jobs:
  include:
    - stage: "Linting & Tests & Sonarcloud analysis"
      name: "Linting & Tests & Sonarcloud analysis"
      script:
        - ng lint
        # - ng test --watch=false --browsers=ChromeHeadless --codeCoverage
        - sonar-scanner
    - stage: "Building & deploying on Firebase"
      name: "Building & deploying on Firebase"
      if: branch = master
      script:
        - ng build --aot --prod --build-optimizer
      deploy:
        provider: firebase
        token:
          secure: "KfFYZIzdu6J7VikgFToCpDglVxjaVkYE1/vCaPrKIoXYa8yI62t3sV60j59VhkxX+1tlEB7InBbK7N7nax6FL6zurIBfYEx52PdiGGOIw2A8fN/ZEHWB4DSXvKWZh33/IfslOk23JoHquYpnTLRb5kFBwy4piJ4yvwXbENUvPwOKNTCxc6Twlbf3MhtyTjkEzYiCGmApc4N5vqfd2NE9qRv/vd3aJEntB65Yi8h1ei+Ol9mdT8HCpX4EsVUx2n0ivAaO8szxf0P6XdOiNrsLQIQJ4LngcL9ZkZFut60N68uF2DNltG6/Kv2PJjYBncueSS4g+NUqlqhqB/i90k5TCtRcNXw0Lk5lJi2B/VJQe+Ya3dpH3jGJfa9C3MtFSUgUOLuiL4kOdDfV6qvmXqDrHnL4+Fu+eSOBPKCLHn2zuZe+lTlft2LL+/IsXeubPm2fwquW0fLHVcujgWkMHIDfYCNiahCuOGSYsjJXIK58wJI5OynGLRJo4aOgjvz6b5Kb56CjiWYfa/0wja/DoDjqPbvVhxa0lqjr4jvxA51tODlKnFutgVLPMHeYsMXsDQfFvEGY/HSVwPsN4RVCE6XkFcLIiC0GOuYx5M5Var5vREawhTeJnxfjFeQ4CibtRYf3OdAHzpC96pmGq8t20l6uzFKAJfP8p6v+VMcA2HzfAr8="
        skip_cleanup: true

git:
  depth: 1
