language: node_js

sudo: false

dist: trusty

node_js:
  - "10"

addons:
  firefox: latest
  sonarcloud:
    organization: "myerffoeg"
    token:
      secure: "rDkguw9nJs1Du8NJk0XnvVY64ELeoyeyH7uYsMV+SKw4H1YXIIVnHLQreuFNMuMEoRfYAq6MZTHGyqPz6BCaUn5M2irflFpbgKiSxOq8udLqlX2V/smgdMypUxlywAaWRxSw+3k1/Y8VYA5yR3ckELh6rU9XAUiMDVDuVWWRgrVmDsKtFi5cY7e5GAKhvgLdABL2Fw/Ga/iF/+nvIBTM9XtFZRD1j6fZWrSa2oXGv949BxXHIDWOsiWukAiy6SwbEkpIYjftL5oYm+QZlvtR0+Im3mvxcdItxkHKQM7+wHWfL0uGEB8O1TDokjI02yB/81tK9xBWg4m1wcdZAooQ9IKBdPnWUvxaIFrtFycTNwtFQ0zUnS4SOIztJgZxWQRh45l8M3PN7yLNoiHM9QhDZ1noNCuW81TxZ+QXiY+RvUf6yIHtj5UOsfPyG5kDlIBpDn5UmFg3EerIzH5coTsPrmwimSkN/IZrV/OpIatRmHU/RL/exQfs6xQywwJ14BVplWB+5zr9/5ODA5V/k5OSKgIYjzOLnKzCQgcRXfDOnJHJXN1MFRS96RNOn/HwV4H3zf+VAcMdS4ZHB32avyulXKGqKNQzrvBa84bE+WAT+FXaJqEZ/GcwC+TWMIqPC3q7A4Jjuqt0ZpbKxZiPTrawI1CkACW4sp6iXetuwrhrNfA="

before_install:
  - npm install -g npm@latest

install:
  - npm install

script:
  - ng lint
  - ng build --prod
  - sonar-scanner

deploy:
  provider: firebase
  token:
    secure: "KfFYZIzdu6J7VikgFToCpDglVxjaVkYE1/vCaPrKIoXYa8yI62t3sV60j59VhkxX+1tlEB7InBbK7N7nax6FL6zurIBfYEx52PdiGGOIw2A8fN/ZEHWB4DSXvKWZh33/IfslOk23JoHquYpnTLRb5kFBwy4piJ4yvwXbENUvPwOKNTCxc6Twlbf3MhtyTjkEzYiCGmApc4N5vqfd2NE9qRv/vd3aJEntB65Yi8h1ei+Ol9mdT8HCpX4EsVUx2n0ivAaO8szxf0P6XdOiNrsLQIQJ4LngcL9ZkZFut60N68uF2DNltG6/Kv2PJjYBncueSS4g+NUqlqhqB/i90k5TCtRcNXw0Lk5lJi2B/VJQe+Ya3dpH3jGJfa9C3MtFSUgUOLuiL4kOdDfV6qvmXqDrHnL4+Fu+eSOBPKCLHn2zuZe+lTlft2LL+/IsXeubPm2fwquW0fLHVcujgWkMHIDfYCNiahCuOGSYsjJXIK58wJI5OynGLRJo4aOgjvz6b5Kb56CjiWYfa/0wja/DoDjqPbvVhxa0lqjr4jvxA51tODlKnFutgVLPMHeYsMXsDQfFvEGY/HSVwPsN4RVCE6XkFcLIiC0GOuYx5M5Var5vREawhTeJnxfjFeQ4CibtRYf3OdAHzpC96pmGq8t20l6uzFKAJfP8p6v+VMcA2HzfAr8="
  skip_cleanup: true

git:
  depth: 1
